spring.application.name=NasaApod
server.port=8081
nasa.api.url=https://api.nasa.gov/planetary/apod
nasa.api.key=fUp11o7yoZ89ynr9AnUamsLKIPrJyoBxTLfJZmXW
nasa.images.api.url=https://images-api.nasa.gov/search
